# Generated by Django 5.2.1 on 2025-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financerecord',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
