# Generated by Django 5.2.1 on 2025-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_date_financerecord_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecord',
            name='user',
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PAID', 'Paid')], max_length=10),
        ),
    ]
