# Generated by Django 5.2.1 on 2025-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
    ]
