# Generated by Django 5.2.1 on 2025-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organization_balance_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='person_in_charge',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
